import pandas as pd
import numpy as np
import os
import sqlite3
from mlflow.exceptions import MlflowException, RestException

from mlflow.deployments.cli import deployment_name

from shared.utils import configure_logging
import logging
import requests
from typing import Any, Optional
from datetime import datetime, timezone
import uuid
import sqlalchemy
import mlflow
from pathlib import Path
from mlflow.tracking import MlflowClient
import tempfile
from mlflow.exceptions import MlflowException
from mlflow.deployments import get_deploy_client

configure_logging()

def apply_drift(mlflow_tracking_uri: str) -> pd.DataFrame:

    mlflow.set_tracking_uri(mlflow_tracking_uri)

    client = MlflowClient(tracking_uri=mlflow_tracking_uri)
    model_version = client.get_model_version_by_alias(
        name="penguin_classifier",
        alias="validated"
    )

    logging.info("Retrieving latest validated URI...")

    model_uri = client.get_model_version_download_uri(
        name=model_version.name,
        version=model_version.version)

    logging.info("Retrieving model version")

    # Get artifact root URI from the run

    run_id = model_version.run_id

    logging.info("Retrieving training data using run_id: %s", run_id)


    dataset_uri = f"{model_uri}/artifacts/dataset.csv"

    with tempfile.TemporaryDirectory() as tmp_dir:
        logging.info("Downloading training data to temp dir: %s", tmp_dir)

        try:
            # Attempt to download the artifact
            local_path = mlflow.artifacts.download_artifacts(artifact_uri=dataset_uri, dst_path=tmp_dir)

            # Verify if the file actually exists before reading
            data = pd.read_csv(local_path)
            logging.info("Training data successfully downloaded and loaded.")

        except MlflowException as e:
            logging.error("MLflow connection or artifact error: %s", e)
            # Handle specifically: e.g., retry logic or raising a custom error
            raise

        except FileNotFoundError:
            logging.error("The file 'train.csv' was not found in the run artifacts.")
            raise

        except Exception as e:
            logging.error("An unexpected error occurred during data retrieval: %s", e)
            raise

    if "species" in data.columns:
        data.pop("species")

    rng = np.random.default_rng()

    data["body_mass_g"] += rng.uniform(
        1,
        3 * data["body_mass_g"].std(),
        size=len(data),
    )

    return data


def generate_traffic(
        data: pd.DataFrame,
        samples: int,
        data_collection_uri: str,

) -> None:
    """
    Generate synthetic traffic by sampling data and creating classifications.

    This function repeatedly samples batches of data, generates classifications
    for each batch, and stores the results in a SQLite database. It continues
    until the specified number of samples have been processed.

    Parameters
    ----------
    data : pd.DataFrame
        The source DataFrame from which to sample data for classification.
        Must contain the required features for generating classifications.
    samples : int
        The target number of samples to generate. The function will continue
        processing batches until at least this many classifications have been
        created.

    Returns
    -------
    None
        This function does not return a value. Results are stored in the
        'inference_data.db' SQLite database.

    Notes
    -----
    - Samples data in batches of 10 rows
    - Replaces NaN, inf, and -inf values with None before processing
    - Stores classification results in 'inference_data.db' via the
        capture_traffic function
    - Logs progress and errors throughout execution
    - Queries and logs the last 5 database entries upon completion

    Examples
    --------
    import pandas as pd
    df = pd.DataFrame({'feature1': [1, 2, 3], 'feature2': [4, 5, 6]})
    generate_traffic(df, samples=100)
    # Generates 100 classifications and stores them in the database

    See Also
    --------
    generate_classifications : Generates classifications from input payload
    capture_traffic : Stores batch data and classifications in the database
    """

    try:
        classifications_generated = 0
        # send data to the endpoint while classifications are less than classifications
        # generated by the model
        while classifications_generated < samples:
            # instantiate dictionary called payload
            payload = {}
            #sample from the drift dataset replacing NaN values with none to ensure
            #compatibility with JSON objects
            batch = data.sample(n=10).replace([np.nan, np.inf, -np.inf], None)
            # generate a dictionary of inputs to send to the enpoint
            payload["inputs"] = [
                {
                    k: (None if pd.isna(v) else v)
                    for k, v in row.to_dict().items()
                }
                for _, row in batch.iterrows()
            ]
            # send inputs to the endpoint
            classifications = generate_classifications(payload)
            print(f"Classifications type: {type(classifications)}, value: {classifications}")
            logging.info(f"Generated classifications %s", classifications)
            try:
                # capture the input data and classifications and save it to the database
                capture_traffic(batch, classifications, data_collection_uri)
            except sqlite3.Error:
                logging.exception(
                    "There was an error connecting to the database. ",
                )
            # update the count of classifications generated
            classifications_generated += len(batch)
            logging.info("Generated %s classifications",classifications_generated)

    except Exception:
        logging.exception("There was an error sending traffic to the endpoint.")

def generate_classifications(payload: dict[str, Any]) \
        -> dict[str, Any] | list[Any] | None:
    """
    Send a classification request to the inference endpoint and return the results.

    This function makes a POST request to a local inference endpoint with the
    provided payload and returns the classification results if successful.

    Parameters
    ----------
    payload : dict[str, Any]
        The input data to be classified. Should contain an 'inputs' key with
        the data formatted according to the endpoint's expected schema.
    endpoint : Optional[str]
        The inference endpoint to send the classification request to.

    Returns
    -------
    dict[str, Any] or list[Any] or None
        The classification results returned by the inference endpoint if the
        request is successful (status code 200). Returns None if the request
        fails or encounters an error.

    Notes
    -----
    - The function sends requests to http://0.0.0.0:8080/invocations
    - Uses JSON content type for the request
    - Logs error information if the response status code is not 200
    - Does not raise exceptions; returns None on failure

    Examples
    --------
    payload = {"inputs": [{"feature1": 1.0, "feature2": 2.0}]}
    result = generate_classifications(payload)
    print(result)
    {'predictions': [0.85, 0.15]}

    invalid_payload = {}
    result = generate_classifications(invalid_payload)
    Error: 400, text: Invalid input format
    print(result)
    None

    See Also
    --------
    generate_traffic : Uses this function to generate classifications in batches
    """
    # locally hosted model URL
    # endpoint = "http://0.0.0.0:8080/invocations"
    # headers = {"Content-Type": "application/json"}
    # response = requests.post(endpoint, json=payload, headers=headers)



    try:

        client = get_deploy_client("sagemaker:/us-east-1")
        response = client.predict(deployment_name="PenguinsEndpoint", inputs=payload["inputs"])

    except RestException as e:
        logging.exception("There was an error sending traffic to the endpoint. %s", e )

    except MlflowException as e:
        logging.exception("There was an error sending traffic to the endpoint: %s", e)

    except Exception as e:
        logging.exception("There was an error sending traffic to the endpoint: %s", e)

    return response


def capture_traffic(model_input: pd.DataFrame,
                    classifications: dict, data_uri: str) -> None:
    logging.info("Storing input payload and predictions in the database...")
    engine = None
    try:
        data = model_input.copy()
        data["date"] = datetime.now(timezone.utc)
        data["classification"] = None
        data["ground_truth"] = None

        if classifications is not None and len(classifications) > 0:
            data["classification"] = [item['classification'] for item in classifications['predictions']]

        data["uuid"] = [str(uuid.uuid4()) for _ in range(len(data))]

        print(f"Attempting to insert {len(data)} rows into database...")
        engine = sqlalchemy.create_engine(data_uri)
        data.to_sql("data", engine, if_exists="append", index=False)
        print(f"Successfully inserted {len(data)} rows.")

    except Exception as e:
        print(f"ERROR: {e}")
        logging.exception(
            "There was an error saving the input request and output prediction "
            "in the database.",
        )
    finally:
        if engine is not None:
            engine.dispose()
